spring:
  application:
    name: kafka-stream-app

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: ks-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"  # or use "org.kerin.model"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Custom config for your app (safe under `ks`)
ks:
  topics:
    error: ks.error